name: deploy key
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: './build'
        branch: 'main'
        commit-message: 'Deploy'
        environment-variables: |
          clientId=${{ secrets.clientId }}
          clientSecret=${{ secrets.clientSecret }}
