name: keys
on:
  workflow_run:
    workflows: ['pages-build-deployment']
    types: [completed]
    branches:
      - main

jobs:
  inject-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: keys
        run: |
          js_file1="js/covers.js"
          js_file2="js/album_data.js"
          clientId="${{ secrets.CLIENTID }}"
          clientSecret="${{ secrets.CLIENTSECRET }}"
          sed -i "s|/\\*INSERT_CLIENT_ID_HERE\\*/|$clientId|g" "$js_file1"
          sed -i "s|/\\*INSERT_CLIENT_SECRET_HERE\\*/|$clientSecret|g" "$js_file2"
  
          echo "keys added: $js_file1"
          echo "keys added: $js_file2"
