name: keys

on:
  workflow_run:
    workflows: ['pages-build-deployment']
    types: [completed]
    branches:
      - main  

jobs:
  inject-secrets-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: repo
        uses: actions/checkout@v4
        with:
          ref: main  

      - name: input keys
        run: |
          js_file1="js/test.js"
          js_file2="js/album_data.js"
          clientId="${{ secrets.CLIENTID }}"
          clientSecret="${{ secrets.CLIENTSECRET }}"
          
          sed -i "s|/\\*INSERT_CLIENT_ID_HERE\\*/|$clientId|g" "$js_file1"
          sed -i "s|/\\*INSERT_CLIENT_SECRET_HERE\\*/|$clientSecret|g" "$js_file2"
          
          echo "keysdone: $js_file1 and $js_file2"

      - name: commit
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add js/test.js js/album_data.js
          git commit -m "Update secrets in JavaScript files"
          git push origin main

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main 
          folder: '.'  
          target-folder: '.' 
          token: ${{ secrets.GITHUB_TOKEN }}  
