name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      
      - name: keys
        run: |
          sed -i 's/{{CLIENT_ID}}/${{ secrets.CLIENT_ID }}/g' js/vars.js
          sed -i 's/{{CLIENT_SECRET}}/${{ secrets.CLIENT_SECRET }}/g' js/vars.js
          
      - uses: peaceiris/actions-gh-pages@v4  
        with:
          branch: main 
          folder: ./  
